version: '3'

services:
  app:
    build:
      dockerfile: BUILD/Dockerfile
      args:
        token: ""
        webpass: "admin"
    image: mageni
    container_name: mageni
    restart: always
    stdin_open: true
    tty: true     
    ports:
      - "443:443"